name: build

on:
  workflow_dispatch:
  schedule:
    # Every 10 min
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: push commit
      run: |
        git commit -m "Commit (automatic)" --allow-empty
        git push
